import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-16 border-b border-gray-200 mb-4 flex items-center px-8">
          <button className='text-sm font-semibold ml-auto block bg-indigo-500 text-white px-4 py-2 rounded-lg'>Login</button>
        </header>
        <div className="grid grid-cols-9">
          <nav className="h-[calc(100vh-5rem)] col-span-2"></nav>
          <main className="col-start-3 col-end-8">
            {children}
          </main>
          <aside className="h-[calc(100vh-5rem)] col-span-2"></aside>
        </div>
      </body>
    </html>
  );
}
