import Header from '@/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'News Feed',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="grid grid-cols-9">
          <nav className="h-[calc(100vh-5rem)] col-span-2"></nav>
          <main className="col-start-3 col-end-8">
            {children}
          </main>
          <aside className="h-[calc(100vh-5rem)] col-span-2"></aside>
        </div>
      </body>
    </html>
  );
}
